#!/bin/bash

(make clean; make)

total=0
totalmax=0

rm -f total.txt *out total.txt

# Test driver
function runtest {
  prog=$1
  args=$2
  testinput=$3
  grade=$4
  inputdescr=
  if [ "$testinput" != "none" ]; then
      inputdescr=" < $testinput"
  fi
  descr="$prog $args $inputdescr"
  
  echo "======= $descr ==========="
  $prog $args < $testinput > $prog.out
  $prog.org $args< $testinput > $prog.org.out
  diff $prog.out $prog.org.out > diff.out
  if [ $? -eq 0 ]; then
      cat $prog.out
      echo Test passed...;
      printf "%-36s: %-3d of %-3d\n" "$descr " $grade $grade >> total.txt
      total=`expr $total + $grade`;
  else
      echo "*****Test Failed*****";
      echo ------ Your Output ----------
      cat $prog.out
      echo ------ Expected Output ------
      cat $prog.org.out
      echo ------ Difference -----------
      cat diff.out
      echo -----------------------------
      printf "%-36s: %-3d of %-3d\n" "$descr " 0 $grade >> total.txt
  fi
  totalmax=`expr $totalmax + $grade`;
  echo
}

# List of tests running
#runtest gauss "" none 6
#runtest gauss "" gauss0.txt 6
runtest gauss "" gauss1.txt 6
#runtest gauss "" gauss2.txt 6
#runtest gauss "" gauss3.txt 6
#runtest gauss "" gauss4.txt 6
#runtest gauss "" gauss5.txt 7
#runtest gauss "" gauss6.txt 7
#runtest newton "" none 7
#runtest newton "pol 1" none 7
#runtest newton "poly1 1" none 7
#runtest newton "sin 0" none 7
#runtest newton "xsin 0" none 7
#runtest newton "poly2 0" none 7
#runtest newton "imaginary 4" none 8

echo
echo
echo   "-------------------------------------------------"
echo   "CS240: Lab 3. $USER   "
echo   "-------------------------------------------------"
cat total.txt
echo   "-------------------------------------------------"
echo   "                              Total: " $total of $totalmax

echo
echo "Hints: "
echo
echo "a) To run only a single test, edit the file testall"
echo "   and comment out the 'runtest' lines of the tests you do not"
echo "   want to run. Make sure to uncomment the lines and run all tests"
echo "   before you turnin your files."
echo
echo "b) You can pause the output by typing "
echo "     testall | less "
echo "   and then type <space> to go down or <ctrl-b> to go up."
echo
