
all: convert getpalin arrange

convert: convert.c
	gcc -g -o convert convert.c

getpalin: getpalin.c
	gcc -g -o getpalin getpalin.c

arrange: arrange.c
	gcc -g -o arrange arrange.c

clean:
	rm -f convert getpalin arrange *out

